- name: Hello World Sample
  hosts: all
  # can't prompt in awx
  #vars_prompt:
  #  - name: var3
  #    prompt: value of var3?
  #    private: no
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello AWX User {{lookup('env', 'HOME')}} on {{inventory_hostname}}"
    - name: Output vars
      debug:
        msg: "var1 = {{var1}} var3 = {{var3}}"

